# acountry
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/acountry.1.gz
complete -c acountry -s d --description 'Print some extra debugging output.'
complete -c acountry -s h -l help --description 'Display this help and exit.'
complete -c acountry -s v --description 'Be more verbose.  Print extra information.'

