# ahost
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/ahost.1.gz
complete -c ahost -s d --description 'Print some extra debugging output.'
complete -c ahost -s h -l help --description 'Display this help and exit.'
complete -c ahost -s t --description 'If type is "a", print the A record (default).'
complete -c ahost -s s --description 'Specify the domain to search instead of using the default values from.'

