# gh-issue-comment
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-issue-comment.1.gz
complete -c gh-issue-comment -s b -l body --description '	Supply a body.  Will prompt for one otherwise.'
complete -c gh-issue-comment -s e -l editor --description '	Add body using editor.'
complete -c gh-issue-comment -s w -l web --description '	Add body in browser OPTIONS INHERITED FROM PARENT COMMANDS.'
complete -c gh-issue-comment -l help --description '	Show help for command.'
complete -c gh-issue-comment -s R -l repo --description '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh is…'

