# gh-repo-fork
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-fork.1.gz
complete -c gh-repo-fork -l clone --description '	Clone the fork {true|false}.'
complete -c gh-repo-fork -l remote --description '	Add remote for fork {true|false}.'
complete -c gh-repo-fork -l remote-name --description '	Specify a name for a fork\'s new remote.'
complete -c gh-repo-fork -l help --description '	Show help for command SEE ALSO.'

