# mdp
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/mdp.1.gz
complete -c mdp -s e -l expand --description 'Enable character entity expansion (e. g.  \'&gt;\' becomes \'>\').'
complete -c mdp -s f -l nofade --description 'Disable color fading in 256 color mode.'
complete -c mdp -s i -l invert --description 'Swap black and white color.'
complete -c mdp -s t -l notrans --description 'Disable transparency in transparent terminal. SS "Miscellaneous Options".'
complete -c mdp -s d -l debug --description 'Enable debug messages on STDERR.  Add multiple times to increases debug level.'
complete -c mdp -s h -l help --description 'Display usage message and exit.'
complete -c mdp -s v -l version --description 'Display version and license information.'
complete -c mdp -l - --description 'or *** characters on a single line.'

